---
data:
  build: jenkins-data
master:
  build: jenkins-master
  ports:
    - "50000:50000"
  volumes_from:
    - data
proxy:
  build: jenkins-proxy
  ports:
    - "80:2015"
  links:
    - "master:jenkins"
